# build environment
FROM node:22-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package*.json .
RUN yarn install
COPY . ./
# ARG API_DOMAIN
# ENV REACT_APP_BASE_URL=${API_DOMAIN}
# RUN set REACT_APP_BASE_URL=${API_DOMAIN}
RUN yarn run build


# production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]